package auth

import (
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/golang-jwt/jwt/v5"
)

// function used for creating jwt for a user
func MakeJWT(userID uuid.UUID, tokenSecret string) (string, error) {

	// create the Claims object
	claims := jwt.RegisteredClaims{
		Issuer: "chirpy-access",
		IssuedAt: jwt.NewNumericDate(time.Now().UTC()),
		ExpiresAt: jwt.NewNumericDate(time.Now().UTC().Add(time.Hour)),			// token will expire in 1 hour
		Subject: userID.String(),
	}

	// create new token
	newToken := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

	// sign the token with secret key
	signingKey := []byte(tokenSecret)
	tokenWithKey, err := newToken.SignedString(signingKey)
	if err != nil {
		return "", fmt.Errorf("Can't sign token with key : %w", err)
	}
	return tokenWithKey, nil
}

// validate the signature of JWT sent from user
func ValidateJWT(tokenString, tokenSecret string) (uuid.UUID, error) {

	// create new empty claim object to be filled
	claims := &jwt.RegisteredClaims{}

	// compare token sent by user with the token generated by server to validate it
	_,err := jwt.ParseWithClaims(tokenString,
		claims,
		func(token *jwt.Token) (interface{}, error) {
			return []byte(tokenSecret), nil
		},
	)
	if err != nil {
		return uuid.Nil, fmt.Errorf("Token is expired or bad signature: %w", err)
	}

	// get userID string from claim Subject
	userIDString := claims.Subject

	// convert user id string to uuid type
	userID, err := uuid.Parse(userIDString)
	if err != nil {
		return uuid.Nil, fmt.Errorf("Error converting string to uuid: %w", err)
	}

	return userID, nil
}


